name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max_old_space_size=8192"

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Git user
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Checkout Main
      run: |
        git checkout main
        git pull origin main

    - name: Bump Version and Push Tag
      id: tag_version
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true

    - name: New Tag
      run: |
        echo "New tag created: ${{ steps.tag_version.outputs.new_tag }}"
      
    - name: Push Production
      run: |
        NEW_TAG=$(echo ${{ steps.tag_version.outputs.new_tag }})
        git checkout -b production $NEW_TAG
        git push origin production --force
